//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_tEST_LETURE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ProductId { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public string ProductName { get; set; }
    }
}
